const sharedPreviewCSS = `
* { box-sizing: border-box; }
body { margin: 0; min-height: 100vh; display: grid; place-items: center; padding: 28px; color: #18221c; background: #ebe7dc; font-family: Arial, sans-serif; }
`;

function makeCase(data) {
  return { level: "Beginner", duration: "5–10 min", ...data };
}

window.CASEBOOK_CASES = {
  "001": makeCase({
    id: "001", fileCode: "CF-001", chapter: "CH01 CSS Fundamentals", topic: "Cascade", title: "The Selector That Wins",
    objective: "Restore the approved status color by diagnosing which CSS rule wins—without changing the trusted HTML.", incidentTitle: "The approved badge turned red.", incident: "A profile card contains an Approved status badge. The general badge rule is correct, but a more specific declaration overrides it inside the card.", evidence: [["Expected", "Green Approved badge"], ["Observed", "Red Approved badge"], ["Constraint", "Do not edit the HTML"]], selector: ".status-badge",
    starterCSS: `.status-badge {\n  background: #315d4c;\n  color: white;\n}\n\n.profile-card .status-badge {\n  background: #a44d2f;\n}`,
    originalCSS: "background:#315d4c;color:white;profile-card background:#a44d2f", targetCSS: "background:#315d4c;color:white", originalCaption: "Original — overridden badge color", targetCaption: "Target — approved forest badge", previewLabel: "status card",
    previewHTML: `<article class="profile-card"><div class="avatar">CE</div><div><p class="name">Christine Espiritu</p><p class="role">Frontend investigator</p></div><span class="status-badge">Approved</span></article>`,
    previewBaseCSS: sharedPreviewCSS + `.profile-card { width: min(100%, 520px); display: grid; grid-template-columns: auto 1fr auto; gap: 16px; align-items: center; padding: 24px; border: 1px solid #738078; border-radius: 8px; background: #fffefa; } .avatar { display: grid; place-items: center; width: 52px; height: 52px; border-radius: 50%; color: white; background: #173d2c; font-weight: 700; } .name { margin: 0 0 5px; font-weight: 700; } .role { margin: 0; color: #657067; font-size: 12px; } .status-badge { padding: 8px 10px; border-radius: 999px; font-size: 11px; font-weight: 700; }`,
    targetPreviewCSS: `.status-badge { background: #315d4c; color: white; }\n.profile-card .status-badge { background: #315d4c; }`,
    hints: [["Observation", "The badge has two background declarations."], ["Concept", "The cascade compares specificity before source order."], ["Targeted clue", "Two class selectors are more specific than one."]], checkingTitle: "Tracing the cascade…", checkingText: " Comparing the badge’s computed color with the approved design.", successText: " The Approved badge now uses the required forest green.", validator: "green-status",
    rootCause: "The descendant selector .profile-card .status-badge has greater specificity than .status-badge, so its red declaration wins.", remember: "When declarations conflict, compare specificity before assuming the nearest-looking rule should win.", recommendedCSS: `.status-badge {\n  background: #315d4c;\n  color: white;\n}\n\n.profile-card .status-badge {\n  background: #315d4c;\n}`,
    question: "Which selector is more specific?", choices: [[".status-badge", false], [".profile-card .status-badge", true]], correctFeedback: "Correct. Two class selectors are more specific than one class selector.", incorrectFeedback: "Not quite. Count the class selectors in each selector.", guideHref: "cases.html", guideLabel: "Back to Case Library →", nextCase: "002", storageKey: "css-casebook-cf001",
  }),
  "002": makeCase({
    id: "002", fileCode: "CF-002", chapter: "CH01 CSS Fundamentals", topic: "Combinators", title: "The Sibling That Would Not Match",
    objective: "Add the divider only between adjacent case items without changing the HTML.", incidentTitle: "The case list lost its dividers.", incident: "Every item should be separated from the item immediately before it, but the current selector targets the wrong relationship.", evidence: [["Expected", "Dividers between items"], ["Observed", "No reliable adjacent divider"], ["Constraint", "Keep the HTML unchanged"]], selector: ".case-list",
    starterCSS: `.case-list {\n  display: grid;\n  gap: 0;\n}\n\n.case-item + .case-item {\n  border-top: 0 solid #738078;\n}`,
    originalCSS: "display:grid;gap:0;border-top:0", targetCSS: "gap:0;border-top:1px solid #738078", originalCaption: "Original — missing sibling divider", targetCaption: "Target — adjacent dividers", previewLabel: "case list",
    previewHTML: `<section class="case-list"><article class="case-item"><strong>01</strong><span>Selectors</span></article><article class="case-item"><strong>02</strong><span>Combinators</span></article><article class="case-item"><strong>03</strong><span>Specificity</span></article></section>`,
    previewBaseCSS: sharedPreviewCSS + `.case-list { width: min(100%, 420px); padding: 8px 20px; border: 1px dashed #738078; background: #fffefa; } .case-item { display: flex; justify-content: space-between; padding: 18px 0; } .case-item strong { color: #a44d2f; font: 700 12px monospace; } .case-item span { font: 600 18px Georgia, serif; }`,
    targetPreviewCSS: `.case-list { display: grid; gap: 0; }\n.case-item + .case-item { border-top: 1px solid #738078; }`,
    hints: [["Observation", "The selector already describes adjacent siblings."], ["Concept", "The selector must apply a visible one-pixel border to items after the first."], ["Targeted clue", "Keep the + relationship and change the border width from 0 to 1px."]], checkingTitle: "Checking the sibling relationship…", checkingText: " Comparing the rendered dividers between adjacent items.", successText: " The list now separates only adjacent case items.", validator: "sibling-divider",
    rootCause: "The adjacent-sibling rule was present, but its border width was zero, so the intended relationship produced no visible divider.", remember: "The + combinator selects an element immediately preceded by a matching sibling.", recommendedCSS: `.case-item + .case-item {\n  border-top: 1px solid #738078;\n}`,
    question: "What does the + combinator select?", choices: [["Every later sibling", false], ["The immediately following sibling", true]], correctFeedback: "Correct. + selects the next matching sibling only.", incorrectFeedback: "Not quite. The general sibling combinator ~ reaches later siblings; + selects the immediate next one.", guideHref: "cases.html", guideLabel: "Back to Case Library →", nextCase: "003", storageKey: "css-casebook-cf002",
  }),
  "003": makeCase({
    id: "003", fileCode: "CF-003", chapter: "CH01 CSS Fundamentals", topic: "Box Model", title: "The Box That Grew",
    objective: "Make the ticket fit its assigned width while keeping its padding and border.", incidentTitle: "The ticket is wider than its column.", incident: "The card is assigned a fixed width, but padding and borders make its rendered box overflow the available track.", evidence: [["Expected", "Ticket fits its 320px column"], ["Observed", "Ticket grows beyond the column"], ["Constraint", "Keep the visual padding"]], selector: ".ticket",
    starterCSS: `.ticket {\n  width: 320px;\n  padding: 24px;\n  border: 4px solid #315d4c;\n  box-sizing: content-box;\n}`,
    originalCSS: "width:320px;padding:24px;border:4px;box-sizing:content-box", targetCSS: "width:320px;padding:24px;border:4px solid #315d4c;box-sizing:border-box", originalCaption: "Original — content-box overflow", targetCaption: "Target — contained ticket", previewLabel: "ticket",
    previewHTML: `<article class="ticket"><strong>Case file 003</strong><p>The box model should keep this ticket inside its assigned column.</p></article>`,
    previewBaseCSS: sharedPreviewCSS + `.ticket { width: 320px; min-height: 150px; color: #fffefa; background: #173d2c; } .ticket strong { font: 700 12px monospace; } .ticket p { max-width: 230px; line-height: 1.5; }`,
    hints: [["Observation", "The declared width excludes padding and border under content-box."], ["Concept", "border-box includes padding and border in the declared width."], ["Targeted clue", "Keep the 320px width, but change the box-sizing model."]], checkingTitle: "Measuring the ticket…", checkingText: " Comparing the rendered box with its assigned width.", successText: " The ticket now fits while retaining its padding and border.", validator: "contained-box",
    rootCause: "content-box adds padding and borders outside the declared width, causing the ticket to render wider than 320px.", remember: "Use border-box when a declared width should include padding and borders.", recommendedCSS: `.ticket {\n  width: 320px;\n  padding: 24px;\n  border: 4px solid #315d4c;\n  box-sizing: border-box;\n}`,
    question: "What does border-box include in the declared width?", choices: [["Only content", false], ["Content, padding and border", true]], correctFeedback: "Correct. border-box keeps padding and border inside the declared dimensions.", incorrectFeedback: "Not quite. content-box excludes padding and border from the declared width.", guideHref: "cases.html", guideLabel: "Back to Case Library →", nextCase: "004", storageKey: "css-casebook-cf003",
  }),
  "004": makeCase({
    id: "004", fileCode: "FX-001", chapter: "CH09 Flexbox", topic: "Flexbox", title: "The Cards That Refuse to Wrap",
    objective: "Keep all three cards inside the case panel when the available width becomes narrow.", incidentTitle: "The cards spill out of the panel.", incident: "The row works on a wide screen but overflows when the case panel narrows. The cards need permission to move onto another line.", evidence: [["Expected", "Cards remain inside the panel"], ["Observed", "The last card overflows"], ["Constraint", "Keep Flexbox and card widths"]], selector: ".card-row",
    starterCSS: `.card-row {\n  display: flex;\n  flex-wrap: nowrap;\n  gap: 12px;\n}`,
    originalCSS: "display:flex;flex-wrap:nowrap;gap:12px", targetCSS: "display:flex;flex-wrap:wrap;gap:12px", originalCaption: "Original — overflowing row", targetCaption: "Target — wrapped cards", previewLabel: "card row",
    previewHTML: `<section class="card-row"><article class="card">Selectors</article><article class="card">Cascade</article><article class="card">Box model</article></section>`,
    previewBaseCSS: sharedPreviewCSS + `.card-row { width: 350px; padding: 16px; border: 1px dashed #738078; background: #fffefa; } .card { flex: 0 0 150px; min-height: 86px; padding: 16px; background: #fdfbf4; border: 1px solid #5c6d62; font-weight: 700; }`,
    hints: [["Observation", "The row is wider than the available panel."], ["Concept", "flex-wrap controls whether items may form additional lines."], ["Targeted clue", "Replace nowrap with the value that permits multiple lines."]], checkingTitle: "Testing the row…", checkingText: " Comparing the rendered cards with the panel bounds.", successText: " The cards now wrap inside the available panel.", validator: "wrapped-row",
    rootCause: "flex-wrap: nowrap forces all flex items onto one line, so the fixed-width cards overflow the narrow panel.", remember: "Flexbox is single-line by default; use flex-wrap: wrap when items must form additional lines.", recommendedCSS: `.card-row {\n  display: flex;\n  flex-wrap: wrap;\n  gap: 12px;\n}`,
    question: "What does flex-wrap: wrap allow?", choices: [["Items to form additional lines", true], ["Items to reverse their HTML order", false]], correctFeedback: "Correct. Wrapping lets flex items continue on another line.", incorrectFeedback: "Not quite. Direction values such as row-reverse change order; wrap controls additional lines.", guideHref: "field-guide.html#lesson-4", guideLabel: "Review wrapping →", nextCase: "005", storageKey: "css-casebook-fx001",
  }),
  "005": makeCase({
    id: "005", fileCode: "FX-002", chapter: "CH09 Flexbox", topic: "Flexbox", title: "The Toolbar Won’t Share Space",
    objective: "Make the toolbar controls share the available row without causing horizontal overflow.", incidentTitle: "The toolbar pushes past its panel.", incident: "Each control keeps its full preferred width, leaving no room for the toolbar container. The controls should share available space.", evidence: [["Expected", "Three controls fit in one row"], ["Observed", "The final control overflows"], ["Constraint", "Keep all controls visible"]], selector: ".toolbar",
    starterCSS: `.toolbar {\n  display: flex;\n  gap: 8px;\n}\n\n.toolbar button {\n  flex: 0 0 150px;\n}`,
    originalCSS: "display:flex;gap:8px;button flex:0 0 150px", targetCSS: "display:flex;gap:8px;button:flex:1 1 0", originalCaption: "Original — rigid toolbar items", targetCaption: "Target — shared toolbar space", previewLabel: "toolbar",
    previewHTML: `<nav class="toolbar"><button>Previous</button><button>Review</button><button>Next</button></nav>`,
    previewBaseCSS: sharedPreviewCSS + `.toolbar { width: 360px; padding: 12px; border: 1px dashed #738078; background: #fffefa; } .toolbar button { min-width: 0; padding: 12px 8px; border: 1px solid #5c6d62; background: #fdfbf4; color: #173d2c; font-weight: 700; }`,
    targetPreviewCSS: `.toolbar { display: flex; gap: 8px; }\n.toolbar button { flex: 1 1 0; }`,
    hints: [["Observation", "Each button insists on 150px even though the row is narrower."], ["Concept", "flex-grow and flex-shrink control how items share free and insufficient space."], ["Targeted clue", "Give each button equal flexible space with flex: 1 1 0."]], checkingTitle: "Balancing the toolbar…", checkingText: " Comparing the rendered controls with the toolbar bounds.", successText: " The controls now share the toolbar without overflow.", validator: "shared-toolbar",
    rootCause: "flex: 0 0 150px disables both growth and shrinking, so the preferred widths cannot adapt to the available row.", remember: "flex: 1 1 0 lets sibling items grow and shrink from an equal basis.", recommendedCSS: `.toolbar {\n  display: flex;\n  gap: 8px;\n}\n\n.toolbar button {\n  flex: 1 1 0;\n}`,
    question: "Which flex shorthand gives an item room to grow and shrink?", choices: [["flex: 0 0 150px", false], ["flex: 1 1 0", true]], correctFeedback: "Correct. The first two values enable growth and shrinking.", incorrectFeedback: "Not quite. 0 0 fixes the item and prevents it from sharing space.", guideHref: "field-guide.html#lesson-5", guideLabel: "Review flex sizing →", nextCase: "006", storageKey: "css-casebook-fx002",
  }),
  "006": makeCase({
    id: "006", fileCode: "FX-003", chapter: "CH09 Flexbox", topic: "Flexbox", title: "The Uneven Gaps",
    objective: "Create consistent spacing between the investigation filters using the Flexbox gap property.", incidentTitle: "The filter row has drifting spacing.", incident: "The first two filters use different margins, so the row looks uneven. The spacing should come from one shared Flexbox rule.", evidence: [["Expected", "Equal 12px spacing"], ["Observed", "The middle gap is larger"], ["Constraint", "Keep the filters in one row"]], selector: ".filter-row",
    starterCSS: `.filter-row {\n  display: flex;\n  gap: 0;\n}\n\n.filter + .filter {\n  margin-left: 24px;\n}`,
    originalCSS: "display:flex;gap:0;filter margin-left:24px", targetCSS: "display:flex;gap:12px;filter margin-left:0", originalCaption: "Original — mixed spacing rules", targetCaption: "Target — consistent Flexbox gap", previewLabel: "filter row",
    previewHTML: `<div class="filter-row"><button class="filter">All cases</button><button class="filter">Playable</button><button class="filter">Planned</button></div>`,
    previewBaseCSS: sharedPreviewCSS + `.filter-row { width: 420px; padding: 18px; border: 1px dashed #738078; background: #fffefa; } .filter { padding: 10px 12px; border: 1px solid #5c6d62; background: #fdfbf4; color: #173d2c; font-weight: 700; }`,
    targetPreviewCSS: `.filter-row { display: flex; gap: 12px; }\n.filter + .filter { margin-left: 0; }`,
    hints: [["Observation", "The spacing is being added by the second and third items separately."], ["Concept", "gap creates consistent space between flex items without item-specific margins."], ["Targeted clue", "Set gap to 12px and neutralize the sibling margin."]], checkingTitle: "Measuring the gaps…", checkingText: " Comparing the distance between each adjacent filter.", successText: " The filters now use one consistent spacing rule.", validator: "even-gaps",
    rootCause: "A 24px sibling margin combined with gap: 0 created spacing that depended on which item was being inspected.", remember: "Prefer gap for consistent spacing between Flexbox items; use margins for relationships that are intentionally asymmetric.", recommendedCSS: `.filter-row {\n  display: flex;\n  gap: 12px;\n}\n\n.filter + .filter {\n  margin-left: 0;\n}`,
    question: "What is the main benefit of gap in a flex row?", choices: [["Consistent spacing between items", true], ["Changing the HTML reading order", false]], correctFeedback: "Correct. gap applies consistent spacing between adjacent flex items.", incorrectFeedback: "Not quite. gap affects spacing, while order and direction affect arrangement.", guideHref: "field-guide.html#lesson-6", guideLabel: "Review distribution →", nextCase: "007", storageKey: "css-casebook-fx003",
  }),
};

const additionalCases = [
  ["007", "CH02 Lists, Links, Backgrounds & Borders", "Lists, Links, Backgrounds & Borders", "The Cropped Hero", "backgroundSize", "contain", "cover", "Make the hero fill its frame without leaving empty bands.", "Cover fills the frame; contain preserves the whole image."],
  ["008", "CH02 Lists, Links, Backgrounds & Borders", "Lists, Links, Backgrounds & Borders", "The Missing Marker", "listStyleType", "none", "circle", "Restore the list marker so the items communicate that they belong to a list.", "A marker is part of the list's visual structure, not decoration to remove by default."],
  ["009", "CH02 Lists, Links, Backgrounds & Borders", "Lists, Links, Backgrounds & Borders", "The Border That Disappeared", "borderStyle", "none", "solid", "Restore the visible border that separates the panel from its background.", "A border needs width, style and color to render as intended."],
  ["010", "CH03 Design Fundamentals", "Design Fundamentals", "The Confusing Interface", "display", "block", "grid", "Give the interface a predictable two-dimensional structure so related information aligns.", "Good structure makes hierarchy easier to see and use."],
  ["011", "CH03 Design Fundamentals", "Design Fundamentals", "The Unclear Checkout", "justifyContent", "flex-start", "space-between", "Separate the checkout summary and primary action across the available row.", "Use alignment to make the next action easy to find."],
  ["012", "CH03 Design Fundamentals", "Design Fundamentals", "The Hierarchy That Collapsed", "fontSize", "14px", "24px", "Restore the heading scale so the primary message is noticed first.", "Hierarchy is the order in which users notice information."],
  ["013", "CH04 Relative & Absolute Units", "Relative & Absolute Units", "The Unpredictable Size", "maxWidth", "100%", "900px", "Keep the content readable by limiting its maximum line length.", "A max-width is a guardrail, not a fixed device size."],
  ["014", "CH04 Relative & Absolute Units", "Relative & Absolute Units", "The Overflowing Viewport", "overflow", "hidden", "auto", "Allow content to be reached when the viewport becomes narrower than the panel.", "Do not clip content when a useful scroll path can preserve it."],
  ["015", "CH04 Relative & Absolute Units", "Relative & Absolute Units", "The Formula That Broke", "maxWidth", "100%", "720px", "Limit the formula-driven content before it becomes an unreadable wall of text.", "Combine fluid sizing with a sensible maximum."],
  ["016", "CH05 Pseudo-classes & Pseudo-elements", "Pseudo-classes & Pseudo-elements", "The Unresponsive Button", "outlineStyle", "none", "solid", "Restore a visible focus indicator when the button receives keyboard focus.", "Focus is an interaction state that must remain visible."],
  ["017", "CH05 Pseudo-classes & Pseudo-elements", "Pseudo-classes & Pseudo-elements", "The Miscounted Child", "fontWeight", "400", "700", "Emphasize the intended structural item without changing the HTML order.", "Check whether the design means nth-child or nth-of-type before styling."],
  ["018", "CH05 Pseudo-classes & Pseudo-elements", "Pseudo-classes & Pseudo-elements", "The Content That Appeared Twice", "borderStyle", "double", "solid", "Use one clear generated-content boundary instead of a doubled visual treatment.", "Pseudo-elements add a visual part; keep the source content singular."],
  ["019", "CH06 CSS Colors", "CSS Colors", "The Invisible Text", "color", "#fffefa", "#173d2c", "Restore enough foreground contrast for the text to remain readable.", "Judge the final foreground and background pair, not either color alone."],
  ["020", "CH06 CSS Colors", "CSS Colors", "The Shadow That Escaped", "boxShadow", "none", "0 4px 12px 0 rgba(0,0,0,.2)", "Bring back the restrained shadow that separates the card from the page.", "Remember box-shadow as X, Y, blur, spread, color."],
  ["021", "CH06 CSS Colors", "CSS Colors", "The Transparent Overlay", "backgroundColor", "rgba(255,255,255,1)", "rgba(255,255,255,.72)", "Restore the translucent overlay so the background remains part of the composition.", "Transparency changes the color users actually perceive."],
  ["022", "CH07 Styling Forms", "Styling Forms", "The Broken Checkbox", "appearance", "auto", "none", "Create a predictable starting point for a custom checkbox while keeping the state work visible.", "appearance: none removes native styling; it does not create the replacement."],
  ["023", "CH07 Styling Forms", "Styling Forms", "The Unclear Error State", "borderColor", "#738078", "#a44d2f", "Make the invalid control state visible without relying on color alone.", "Error styling should be obvious and should support the message text."],
  ["024", "CH07 Styling Forms", "Styling Forms", "The Label That Lost Its Target", "display", "none", "block", "Keep the label present so the control remains understandable and usable.", "A visible, associated label is not a placeholder."],
  ["025", "CH08 Layouts & Effects", "Layouts & Effects", "The Overflowing Card", "overflow", "visible", "hidden", "Contain the decorative edge treatment inside the card boundary.", "Clip only content that is intentionally decorative or safely replaceable."],
  ["026", "CH08 Layouts & Effects", "Layouts & Effects", "The Unexpected Extra Width", "boxSizing", "content-box", "border-box", "Keep the declared card width inclusive of its padding and border.", "border-box includes content, padding and border in the declared size."],
  ["027", "CH08 Layouts & Effects", "Layouts & Effects", "The Transforming Hit Area", "transform", "none", "translateY(-4px)", "Lift the card visually without changing the layout space reserved for it.", "Transforms move pixels; they do not rewrite normal flow."],
  ["028", "CH10 CSS Typography", "CSS Typography", "The Misaligned Heading", "fontWeight", "400", "700", "Restore the heading weight so its role is clear in the type hierarchy.", "Weight is one part of hierarchy; line-height and contrast matter too."],
  ["029", "CH10 CSS Typography", "CSS Typography", "The Missing Web Font", "fontFamily", "Arial", "Georgia", "Apply the intended display face while retaining a predictable fallback in the stack.", "A fallback is part of the design, not an afterthought."],
  ["030", "CH10 CSS Typography", "CSS Typography", "The Line-height That Drifted", "lineHeight", "1", "1.6", "Restore enough line spacing for the paragraph to remain readable.", "Leading controls the distance between lines; it is not the same as tracking."],
  ["031", "CH11 CSS Accessibility", "CSS Accessibility", "The Invisible Focus", "outlineStyle", "none", "solid", "Restore the visible focus ring required for keyboard navigation.", "If focus disappears, keyboard users lose their place."],
  ["032", "CH11 CSS Accessibility", "CSS Accessibility", "The Hidden-but-Readable Button", "maxWidth", "0px", "240px", "Keep the accessible button text available within a usable visual area.", "Visual hiding and semantic hiding are different jobs."],
  ["033", "CH11 CSS Accessibility", "CSS Accessibility", "The Contrast That Failed", "color", "#fffefa", "#173d2c", "Restore a darker text color that can be checked against the light surface.", "Do not communicate meaning through color alone."],
  ["034", "CH12 CSS Positioning", "CSS Positioning", "The Stubborn Navbar", "position", "static", "sticky", "Keep the navigation available while the user moves through a long case file.", "Sticky remains in flow until it reaches its inset threshold."],
  ["035", "CH12 CSS Positioning", "CSS Positioning", "The Badge in the Wrong Corner", "position", "static", "absolute", "Anchor the badge to the positioned card instead of the page flow.", "Absolute positioning needs a containing block you can name."],
  ["036", "CH12 CSS Positioning", "CSS Positioning", "The Layer Behind the Modal", "zIndex", "0", "100", "Place the modal layer above the page content within its stacking context.", "A large z-index cannot escape an ancestor stacking context."],
  ["037", "CH13 Attribute Selectors", "Attribute Selectors", "The Selector Mystery", "textDecorationLine", "none", "underline", "Make the attribute-matched link visibly distinct from ordinary text.", "Start from the attribute relationship, then add only the specificity you need."],
  ["038", "CH13 Attribute Selectors", "Attribute Selectors", "The Wrong Download Link", "color", "#173d2c", "#a44d2f", "Signal the PDF download link with the intended file-type treatment.", "The $= operator matches the end of an attribute value."],
  ["039", "CH13 Attribute Selectors", "Attribute Selectors", "The Language That Was Missed", "fontStyle", "normal", "italic", "Apply the language-specific typographic cue to the matched content.", "The |= operator matches a language token such as en or en-US."],
  ["040", "CH14 Responsive Web Design", "Responsive Web Design", "The Broken Mobile Layout", "maxWidth", "none", "100%", "Keep the content surface within the viewport on narrow screens.", "Fluid foundations come before breakpoint rules."],
  ["041", "CH14 Responsive Web Design", "Responsive Web Design", "The Desktop-only Button", "display", "none", "block", "Make the action available when the responsive layout calls for it.", "A responsive change should preserve access to essential actions."],
  ["042", "CH14 Responsive Web Design", "Responsive Web Design", "The Breakpoint That Came Too Early", "overflow", "hidden", "auto", "Preserve access to the layout when its content exceeds the available width.", "A breakpoint should mark a content change, not a device label."],
  ["043", "CH15 CSS Grid", "CSS Grid", "The Collapsed Gallery", "display", "block", "grid", "Restore the two-dimensional gallery layout.", "Grid is the right model when rows and columns matter together."],
  ["044", "CH15 CSS Grid", "CSS Grid", "The Misplaced Sidebar", "gridTemplateColumns", "1fr", "200px 1fr", "Give the sidebar its track and let the main content use the remaining space.", "Define the track structure before placing items."],
  ["045", "CH15 CSS Grid", "CSS Grid", "The Track That Would Not Stretch", "gridColumn", "auto", "1 / -1", "Make the banner span the full explicit grid width.", "1 / -1 spans from the first grid line to the last."],
  ["046", "CH16 CSS Animations", "CSS Animations", "The Animation That Never Ends", "animationIterationCount", "infinite", "1", "Let the entrance animation finish instead of repeating forever.", "Iteration count controls repeats; essential information should not depend on motion."],
  ["047", "CH16 CSS Animations", "CSS Animations", "The Button That Moves Too Much", "animationDuration", "100ms", "600ms", "Slow the movement enough that the action remains comfortable to follow.", "Use timing as communication, not as noise."],
  ["048", "CH16 CSS Animations", "CSS Animations", "The Motion That Ignored Preferences", "animationName", "fadeIn", "none", "Respect a reduced-motion preference by disabling the nonessential animation.", "Reduced motion is a user preference, not a design failure."],
];

const genericPreviewBase = sharedPreviewCSS + `.case-surface { width: min(100%, 520px); min-height: 160px; display: flex; flex-direction: column; justify-content: center; gap: 12px; padding: 28px; border: 1px dashed #738078; background: #fffefa; color: #18221c; } .case-surface strong { color: #a44d2f; font: 700 11px monospace; text-transform: uppercase; letter-spacing: .08em; } .case-surface h3 { margin: 0; font: 600 26px/1.1 Georgia, serif; } .case-surface p { margin: 0; color: #657067; line-height: 1.5; }`;

additionalCases.forEach(([id, chapter, topic, title, property, starter, target, objective, remember], index) => {
  const nextCase = String(Number(id) + 1).padStart(3, "0");
  const isLast = id === "048";
  const selector = ".case-surface";
  const cssProperty = property.replace(/[A-Z]/g, (char) => `-${char.toLowerCase()}`);
  const layoutPrefix = property === "gridTemplateColumns" || property === "gridColumn" ? "display: grid; " : "";
  const keyframes = property === "animationName" && starter === "fadeIn" ? "@keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }\n" : "";
  const previewTarget = `${keyframes}${selector} { ${layoutPrefix}${cssProperty}: ${target}; }`;
  const caseCode = chapter.slice(2, 4) === "09" ? "FX" : `C${chapter.slice(2, 4)}`;
  window.CASEBOOK_CASES[id] = makeCase({
    id, fileCode: `${caseCode}-${String(index + 4).padStart(3, "0")}`, chapter, topic, title,
    objective, incidentTitle: `${title} needs investigation.`, incident: `The ${title.toLowerCase()} report points to one CSS declaration that no longer matches the intended interface behavior. Trace the rendered result, then restore the trusted design rule.`, evidence: [["Expected", "The documented design behavior"], ["Observed", "A visible CSS failure"], ["Constraint", "Keep the trusted HTML"]], selector,
    starterCSS: `${selector} {\n  ${cssProperty}: ${starter};\n}`, originalCSS: `${cssProperty}:${starter}`, targetCSS: `${layoutPrefix}${cssProperty}:${target}`, targetPreviewCSS: previewTarget, originalCaption: `Original — ${title.toLowerCase()}`, targetCaption: `Target — resolved ${title.toLowerCase()}`, previewLabel: "case surface",
    previewHTML: `<article class="case-surface"><strong>Investigation ${id}</strong><h3>${title}</h3><p>Inspect the rendered surface, then restore the intended CSS behavior.</p></article>`, previewBaseCSS: genericPreviewBase,
    hints: [["Observation", `Inspect the computed ${cssProperty} value on the case surface.`], ["Concept", `The ${cssProperty} declaration controls the behavior described in the incident.`], ["Targeted clue", `Try the documented target value: ${cssProperty}: ${target}.`]], checkingTitle: `Inspecting ${cssProperty}…`, checkingText: " Comparing the rendered result with the trusted target.", successText: " The rendered case surface now matches the target behavior.", validator: "computed-style", expectedProperty: property, expectedValue: target,
    rootCause: `The starter rule set ${cssProperty} to ${starter}, which caused the rendered result to diverge from the intended behavior.`, remember, recommendedCSS: `${selector} {\n  ${layoutPrefix}${cssProperty}: ${target};\n}`,
    question: `Which value resolves this case?`, choices: [[target, true], [starter, false]], correctFeedback: `Correct. ${cssProperty}: ${target} restores the documented behavior.`, incorrectFeedback: `Not quite. The target value is ${cssProperty}: ${target}.`, guideHref: `field-guide.html#chapter-${chapter.slice(2, 4)}`, guideLabel: `Review ${topic} →`, nextCase: isLast ? null : nextCase, storageKey: `css-casebook-c${id}`,
  });
});

Object.assign(window.CASEBOOK_CASES, {
  "007": makeCase({
    id: "007", fileCode: "LB-001", chapter: "CH02 Lists, Links, Backgrounds & Borders", topic: "Backgrounds", title: "The Cropped Hero",
    objective: "Make the case-study hero fill its banner while keeping the focal subject visible.", incidentTitle: "The hero image left empty bands.", incident: "The editorial hero uses a landscape image inside a wide banner. The current sizing preserves the whole image, but leaves distracting empty space around it.", evidence: [["Expected", "Banner is fully covered"], ["Observed", "Empty bands around the image"], ["Constraint", "Keep the focal subject centered"]], selector: ".hero-banner", starterCSS: `.hero-banner {\n  background-image: url("hero.jpg");\n  background-size: contain;\n  background-position: center;\n  background-repeat: no-repeat;\n}`, originalCSS: "background-size:contain", targetCSS: "background-size:cover", targetPreviewCSS: `.hero-banner { background-image: linear-gradient(120deg, #173d2c, #9fc5ad); background-size: cover; background-position: center; background-repeat: no-repeat; }`, originalCaption: "Original — contained hero", targetCaption: "Target — covered hero", previewLabel: "hero banner", previewHTML: `<article class="hero-banner"><span>FIELD NOTE 07</span><h2>Read the evidence</h2><p>Backgrounds should support the story, not expose the empty canvas.</p></article>`, previewBaseCSS: sharedPreviewCSS + `.hero-banner { width: min(100%, 560px); min-height: 220px; display: flex; flex-direction: column; justify-content: flex-end; gap: 10px; padding: 28px; color: #fffefa; background-color: #173d2c; border: 1px dashed #738078; } .hero-banner span { font: 700 10px monospace; letter-spacing: .12em; } .hero-banner h2 { margin: 0; font: 600 34px/1 Georgia, serif; } .hero-banner p { max-width: 330px; margin: 0; line-height: 1.5; }`, hints: [["Observation", "The banner is wider than the source image's natural ratio."], ["Concept", "contain keeps the whole image visible; cover fills the box and may crop."], ["Targeted clue", "Change only background-size from contain to cover."]], checkingTitle: "Inspecting the hero…", checkingText: " Comparing the rendered banner with the editorial target.", successText: " The hero now fills the banner without empty bands.", validator: "computed-style", expectedProperty: "backgroundSize", expectedValue: "cover", rootCause: "background-size: contain preserved the entire image at the cost of empty space in the banner.", remember: "Cover fills the box; contain preserves the whole image.", recommendedCSS: `.hero-banner {\n  background-size: cover;\n  background-position: center;\n}`, question: "Which value fills the entire background box?", choices: [["contain", false], ["cover", true]], correctFeedback: "Correct. cover fills the box and may crop the image.", incorrectFeedback: "Not quite. contain keeps the whole image visible and may leave empty space.", guideHref: "field-guide.html#chapter-02", guideLabel: "Review backgrounds →", nextCase: "008", storageKey: "css-casebook-c007" }),
  "008": makeCase({
    id: "008", fileCode: "LB-002", chapter: "CH02 Lists, Links, Backgrounds & Borders", topic: "Lists", title: "The Missing Marker",
    objective: "Restore the list marker so the evidence items read as a deliberate collection.", incidentTitle: "The evidence list lost its visual structure.", incident: "The evidence panel contains three related findings, but the markers were removed. Without them, the items look like disconnected paragraphs.", evidence: [["Expected", "Clear list markers"], ["Observed", "Unmarked evidence items"], ["Constraint", "Keep the semantic list"]], selector: ".evidence-list", starterCSS: `.evidence-list {\n  list-style-type: none;\n  list-style-position: outside;\n}`, originalCSS: "list-style-type:none", targetCSS: "list-style-type:circle", targetPreviewCSS: `.evidence-list { list-style-type: circle; list-style-position: outside; }`, originalCaption: "Original — markers removed", targetCaption: "Target — visible markers", previewLabel: "evidence list", previewHTML: `<ul class="evidence-list"><li><strong>Expected</strong> Focus ring remains visible</li><li><strong>Observed</strong> Keyboard focus disappears</li><li><strong>Constraint</strong> Keep the native button</li></ul>`, previewBaseCSS: sharedPreviewCSS + `.evidence-list { width: min(100%, 470px); margin: 0; padding: 24px 28px 24px 48px; border: 1px dashed #738078; background: #fffefa; color: #18221c; } .evidence-list li { padding: 10px 0; border-bottom: 1px solid #d5d8d1; line-height: 1.5; } .evidence-list li:last-child { border-bottom: 0; } .evidence-list strong { color: #a44d2f; font: 700 10px monospace; letter-spacing: .08em; }`, hints: [["Observation", "The HTML is already a ul with li items."], ["Concept", "list-style-type controls the marker shape; it does not change the semantic list."], ["Targeted clue", "Restore a circle marker without changing the list position."]], checkingTitle: "Checking the evidence list…", checkingText: " Comparing the marker treatment with the casebook pattern.", successText: " The evidence list now reads as a structured collection.", validator: "computed-style", expectedProperty: "listStyleType", expectedValue: "circle", rootCause: "The list marker was explicitly removed with list-style-type: none.", remember: "A list marker is part of the list's visual structure, not decoration to remove by default.", recommendedCSS: `.evidence-list {\n  list-style-type: circle;\n  list-style-position: outside;\n}`, question: "Which property chooses a list marker shape?", choices: [["list-style-type", true], ["list-style-position", false]], correctFeedback: "Correct. list-style-type chooses disc, circle, decimal and other marker styles.", incorrectFeedback: "Not quite. list-style-position controls where the marker sits relative to the list content.", guideHref: "field-guide.html#chapter-02", guideLabel: "Review lists →", nextCase: "009", storageKey: "css-casebook-c008" }),
  "009": makeCase({
    id: "009", fileCode: "LB-003", chapter: "CH02 Lists, Links, Backgrounds & Borders", topic: "Borders", title: "The Border That Disappeared",
    objective: "Restore the boundary around the trusted evidence panel without changing its spacing.", incidentTitle: "The card lost its boundary.", incident: "The evidence panel still has the correct padding and color, but its edge blends into the page because the border style was removed.", evidence: [["Expected", "A clear panel boundary"], ["Observed", "Panel blends into the page"], ["Constraint", "Keep width and padding"]], selector: ".evidence-card", starterCSS: `.evidence-card {\n  border-width: 1px;\n  border-style: none;\n  border-color: #738078;\n  border-radius: 12px;\n}`, originalCSS: "border-style:none", targetCSS: "border-style:solid", targetPreviewCSS: `.evidence-card { border-width: 1px; border-style: solid; border-color: #738078; border-radius: 12px; }`, originalCaption: "Original — boundary removed", targetCaption: "Target — defined panel", previewLabel: "bordered card", previewHTML: `<article class="evidence-card"><span>CASE NOTE</span><h2>Why borders matter</h2><p>A quiet boundary helps users group related evidence before they read every line.</p></article>`, previewBaseCSS: sharedPreviewCSS + `.evidence-card { width: min(100%, 500px); min-height: 190px; padding: 28px; background: #fffefa; color: #18221c; } .evidence-card span { color: #a44d2f; font: 700 10px monospace; letter-spacing: .12em; } .evidence-card h2 { margin: 14px 0 8px; font: 600 28px/1.1 Georgia, serif; } .evidence-card p { max-width: 360px; margin: 0; color: #657067; line-height: 1.55; }`, hints: [["Observation", "The card has a border width and color, but no border style."], ["Concept", "A border needs width, style and color before it becomes visible."], ["Targeted clue", "Use the standard solid border style."]], checkingTitle: "Inspecting the panel edge…", checkingText: " Comparing the rendered boundary with the evidence card target.", successText: " The evidence card now has a clear, restrained boundary.", validator: "computed-style", expectedProperty: "borderStyle", expectedValue: "solid", rootCause: "border-style: none disables the border even though width and color remain declared.", remember: "A border shorthand usually follows width, style, then color.", recommendedCSS: `.evidence-card {\n  border: 1px solid #738078;\n  border-radius: 12px;\n}`, question: "Which border declaration makes the edge render?", choices: [["border-style: solid", true], ["border-style: none", false]], correctFeedback: "Correct. A visible style completes the border definition.", incorrectFeedback: "Not quite. none explicitly removes the border edge.", guideHref: "field-guide.html#chapter-02", guideLabel: "Review borders →", nextCase: "010", storageKey: "css-casebook-c009" }),
});
