const chapters = [
  { number: "01", title: "CSS Fundamentals", deck: "Build a reliable CSS mental model: selectors, sizing, spacing, display, combinators and the cascade.", objectives: ["Read a CSS rule from selector to value.", "Choose the right selector relationship.", "Explain why a declaration wins."], before: "Know basic HTML elements and attributes.", lessons: [
    ["CSS rules and the viewport", "CSS controls presentation while HTML supplies structure and content. The viewport meta element tells mobile browsers to size the page to the device width.", '<meta name="viewport" content="width=device-width, initial-scale=1.0">', "If spacing appears from nowhere, check browser defaults before adding another rule."],
    ["Sizing, display and spacing", "Block elements start on a new line; inline elements stay in text flow; inline-block sits inline while accepting width and height. Margin creates space outside the border, while padding creates space inside it.", ".box {\n  display: inline-block;\n  margin: 10px;\n  padding: 12px;\n}", "Margin separates siblings. Padding protects the content from its border."],
    ["Combinators and the cascade", "A space selects descendants, > selects direct children, + selects the immediately following sibling, and ~ selects later matching siblings. When rules conflict, compare importance and origin, then specificity, then source order.", ".card h2 + p { margin-top: 0; }\n.profile .status { color: seagreen; }", "Do not reach for !important before inspecting the selector that wins."],
  ]},
  { number: "02", title: "Lists, Links, Backgrounds and Borders", deck: "Style common interface surfaces without losing interaction states, image intent or readable contrast.", objectives: ["Control list markers and link states.", "Choose cover or contain intentionally.", "Build clear borders, gradients and contrast."], before: "Know selectors, color values and basic spacing.", lessons: [
    ["Lists and link states", "Use list-style properties for markers and spacing. Links have distinct states: :link, :visited, :hover, :focus and :active. A focus style must remain visible for keyboard users.", "ul { list-style-position: outside; }\na:hover { text-decoration: underline; }\na:focus { outline: 2px solid currentColor; }", "Hover is not a substitute for focus."],
    ["Background images", "background-size: cover fills the box and may crop the image. contain keeps the whole image visible and may leave empty space. Pair either choice with a deliberate position and repeat value.", ".hero {\n  background-size: cover;\n  background-position: center;\n  background-repeat: no-repeat;\n}", "Cover fills. Contain preserves the whole image."],
    ["Borders, gradients and contrast", "Border shorthand follows width, style and color. Linear gradients travel along a direction; radial gradients radiate from a center. Check normal text at 4.5:1 contrast and large text at 3:1.", ".card { border: 1px solid #738078; border-radius: 12px; }\n.banner { background-image: linear-gradient(to right, navy, skyblue); }", "A decorative gradient still needs readable text on top."],
  ]},
  { number: "03", title: "Design Fundamentals", deck: "Turn CSS decisions into interfaces with hierarchy, balance, white space and user-centered intent.", objectives: ["Recognize hierarchy, contrast and balance.", "Connect interface patterns to user needs.", "Use prototypes and testing to reduce guesswork."], before: "Know basic layout and typography properties.", lessons: [
    ["Hierarchy and composition", "Hierarchy answers what users should notice first. Composition describes how all visual elements work together. Alignment makes relationships predictable; white space gives those relationships room to breathe.", "Design check: What should be noticed first? What should be grouped? What can be removed?", "Hierarchy is attention order, not just bigger text."],
    ["UI, UX and requirements", "UI is the visible interactive interface. UX is the overall experience. A design brief records goals, constraints and requirements so a polished screen still solves the right problem.", "Requirement: A learner can reach the next case without losing their progress.", "A beautiful interface that misses a user requirement is still a failed design."],
    ["Patterns and research", "Cards should stay focused, breadcrumbs show location, progress indicators show position in a flow, and progressive disclosure reveals complexity when it is needed. Use user research, testing and A/B comparisons to validate assumptions.", "Test one task: Can a first-time user find the next action without explanation?", "Prefer evidence from user behavior over personal preference."],
  ]},
  { number: "04", title: "Relative and Absolute Units", deck: "Choose units that respond to the right reference: the viewport, the root, the parent or the current font context.", objectives: ["Distinguish absolute and relative units.", "Predict em versus rem sizing.", "Use percentages and calc without overflow."], before: "Know width, height and font-size.", lessons: [
    ["Absolute units", "px is the screen unit you will use most often. Physical units such as in, cm, mm, pt and pc are more common in print-oriented CSS and are still defined through CSS reference pixels.", ".print-label { font-size: 12pt; }\n.screen-control { min-height: 44px; }", "Use px when a screen measurement needs a predictable reference."],
    ["Relative units", "Percentages usually refer to a parent dimension. em depends on the local font-size context and can compound. rem refers to the root html font size. vh and vw refer to viewport height and width.", "html { font-size: 16px; }\n.card p { font-size: 1.25em; }\n.title { font-size: 2rem; }", "em is contextual; rem is root-relative."],
    ["calc and fluid sizing", "calc() combines values and units. Keep spaces around + and - so the expression parses reliably. Combine a fluid value with min-width or max-width when the design needs guardrails.", ".main { width: calc(100% - 40px); max-width: 900px; }", "A formula is useful only when its smallest and largest results are still usable."],
  ]},
  { number: "05", title: "Pseudo-classes and Pseudo-elements", deck: "Style states, structural positions and generated parts without changing the HTML for every visual detail.", objectives: ["Separate state selectors from generated content.", "Use structural and functional pseudo-classes.", "Avoid confusing child position with element type."], before: "Know class selectors and basic form controls.", lessons: [
    ["Interaction and input states", "Pseudo-classes describe conditions: hover, focus, focus-within, checked, valid, invalid, disabled and required. They let CSS respond to user action and form state.", ".form-group:focus-within { border-color: royalblue; }\ninput:invalid { border-color: crimson; }", "Focus-within matches the group when the group or one of its descendants has focus."],
    ["Structural selectors", "first-child and nth-child count all siblings. first-of-type and nth-of-type count only siblings of the same element type. :target matches the element named by the URL fragment.", "li:nth-child(odd) { background: #f5f5f5; }\np:first-of-type { margin-top: 0; }", "Ask whether you mean the nth child or the nth element of this type."],
    ["Functional selectors and pseudo-elements", ":is() groups selectors, :where() groups with zero specificity, :has() reacts to related content, and :not() excludes a match. ::before and ::after create generated parts and need content when used visibly.", ".required::after { content: ' *'; }\narticle:has(h2) { border: 1px solid; }", ":hover is a state. ::before is a generated part."],
  ]},
  { number: "06", title: "CSS Colors", deck: "Use color systems, transparency, shadows and gradients to create hierarchy without sacrificing readability.", objectives: ["Choose a useful color format.", "Layer shadows and gradients intentionally.", "Preserve contrast when colors change."], before: "Know background, border and color properties.", lessons: [
    ["Color systems", "Named colors are quick but limited. Hex expresses RGB in base 16; rgb and rgba separate channels and transparency; HSL expresses hue, saturation and lightness for easier adjustments.", ".badge { background: hsl(160 40% 28%); color: rgb(255 255 255); }", "Use a format that makes the next change easy to reason about."],
    ["Shadows", "Remember box-shadow as X, Y, blur, spread, color. Positive X moves right and positive Y moves down. Multiple shadows are comma-separated and layered front to back; inset puts the shadow inside.", "box-shadow: 0 4px 12px 0 rgba(0, 0, 0, .2);\nbox-shadow: inset 0 0 8px #999;", "Blur softens. Spread expands or contracts."],
    ["Gradients and transparency", "Linear gradients move along a line; radial gradients radiate from a point. Transparent colors reveal layers beneath, so inspect the final combined contrast rather than one color in isolation.", "background: linear-gradient(to right, #173d2c, #9fc5ad);", "A transparent overlay changes the color users actually perceive."],
  ]},
  { number: "07", title: "Styling Forms", deck: "Make controls readable, focusable and state-aware while respecting native behavior where it helps users.", objectives: ["Style focus without hiding it.", "Rebuild states after removing native appearance.", "Test special controls across browsers."], before: "Know labels, inputs and basic pseudo-classes.", lessons: [
    ["Accessible input styling", "Use readable text, enough contrast and a clearly visible focus indicator. Never remove an outline without replacing it with an equally obvious state.", "input:focus { outline: 3px solid royalblue; outline-offset: 2px; }", "A focus state is part of the interface, not decoration."],
    ["appearance none", "appearance: none removes much of the browser's native control styling; it does not create a custom control for you. Recreate checked, disabled, focus and error states deliberately.", "input[type='checkbox'] { appearance: none; }\ninput:checked { background: seagreen; }", "If you remove the native state, you own every replacement state."],
    ["Special inputs and labels", "datetime-local and color controls rely on browser-specific UI. Test them in multiple browsers. A visible placeholder is not a replacement for a properly associated label.", "<label for='start-date'>Start date</label>\n<input id='start-date' type='datetime-local'>", "Labels explain controls and expand their usable click target."],
  ]},
  { number: "08", title: "Layouts and Effects", deck: "Control overflow, transforms, box sizing, resets, visibility and filters without creating hidden layout problems.", objectives: ["Diagnose overflow in both axes.", "Predict the box model.", "Use effects without breaking access or interaction."], before: "Know width, padding, border and display.", lessons: [
    ["Overflow", "overflow controls content larger than its box. Use hidden to clip, auto to add scrolling when needed, or two values for x and y. Check whether the content should wrap, shrink or scroll before clipping it.", ".panel { overflow-x: auto; overflow-y: hidden; }", "Hiding overflow can hide the symptom while trapping real content."],
    ["Transforms and filters", "Transforms move, resize, rotate or skew the visual box without changing normal flow. Filters change appearance, such as grayscale or blur. Visually moving content off-screen does not necessarily hide it from assistive technology.", ".card:hover { transform: translateY(-4px) scale(1.02); }\nimg { filter: grayscale(100%); }", "Visual movement and semantic visibility are different concerns."],
    ["Box model, resets and visibility", "The box model runs content, padding, border, margin from inside to outside. border-box includes padding and border in the declared size. Reset or normalize defaults when predictable starting styles matter.", "*, *::before, *::after { box-sizing: border-box; }", "Margin is outside; it can collapse vertically with adjacent margins."],
  ]},
  { number: "09", title: "CSS Flexbox", deck: "Understand one-dimensional layout through axes, direction, wrapping and alignment, then apply the model in a live control room.", objectives: ["Identify main and cross axes.", "Control direction, wrapping and distribution.", "Diagnose an alignment or sizing failure."], before: "Know basic declarations, selectors, width and height.", lessons: [
    ["Main and cross axes", "A flex container has a main axis and a perpendicular cross axis. flex-direction chooses the main axis; the cross axis runs across it.", ".container { display: flex; }", "The main axis is not always horizontal."],
    ["Direction and wrapping", "row and row-reverse create a horizontal main axis; column and column-reverse create a vertical one. nowrap keeps one line; wrap permits additional lines; wrap-reverse reverses cross-axis stacking.", "flex-flow: row wrap;", "Changing direction changes what justify-content means."],
    ["Distribution and centering", "justify-content follows the main axis. align-items works on the cross axis. To center a row in both directions, the container needs available space plus center on both properties.", ".container {\n  display: flex;\n  justify-content: center;\n  align-items: center;\n}", "JUSTIFY follows MAIN. ALIGN-ITEMS crosses it."]
  ], lab: true},
  { number: "10", title: "CSS Typography", deck: "Choose type families, spacing and effects that support hierarchy, readability and graceful fallback.", objectives: ["Use type vocabulary accurately.", "Build resilient font stacks.", "Control line height, shadows and loading."], before: "Know color, spacing and basic text properties.", lessons: [
    ["Type anatomy", "A typeface is a design family; a font is a specific variation or file. Baseline, cap height, x-height, ascenders and descenders describe how letterforms occupy space.", "Typography checklist: family, size, weight, line-height, width and contrast.", "Kerning is pair spacing; tracking is spacing across a range; leading is line spacing."],
    ["Families and fallbacks", "font-family lists preferences in order and should end with a generic family. Serif, sans-serif and monospace communicate different visual structures.", "body { font-family: 'Roboto', Arial, sans-serif; }", "A fallback is part of the design, not an afterthought."],
    ["Web fonts and text shadows", "@font-face registers a hosted font; WOFF2 is a common preferred format. font-display: swap helps text appear while the font loads. Text shadows use offset-x, offset-y, blur and color; they have no spread value.", "@font-face { font-family: 'SiteFont'; src: url('fonts/site.woff2') format('woff2'); font-display: swap; }", "Keep type readable before and after the custom font loads."],
  ]},
  { number: "11", title: "CSS Accessibility", deck: "Keep meaningful structure, contrast, focus, hiding behavior and motion preferences aligned with assistive technology.", objectives: ["Separate visual hiding from semantic hiding.", "Preserve contrast and focus.", "Respect reduced-motion preferences."], before: "Know pseudo-classes, media queries and basic HTML semantics.", lessons: [
    ["Contrast and the accessibility tree", "The accessibility tree exposes meaningful structure and controls to assistive technology. Do not communicate meaning through color alone. Normal text needs 4.5:1 contrast and large text 3:1 under WCAG AA targets.", "Pair a status color with a word, icon or shape that carries the same meaning.", "If color disappears, the message should still survive."],
    ["Hiding content", "display: none and the hidden attribute usually remove content from layout and the accessibility tree. visibility: hidden preserves space but normally hides content from assistive technology. aria-hidden hides from assistive technology but not necessarily visually and must not be applied to focusable controls.", ".sr-only { position: absolute; width: 1px; height: 1px; overflow: hidden; clip: rect(0,0,0,0); }", "Visual hiding and semantic hiding are different jobs."],
    ["Motion and labels", "Use prefers-reduced-motion to remove unnecessary animation. A placeholder cannot replace a visible, associated label. Essential information should never depend only on animation.", "@media (prefers-reduced-motion: reduce) { .card { animation: none; } }", "Reduce motion; do not reduce meaning."],
  ]},
  { number: "12", title: "CSS Positioning", deck: "Place elements intentionally with flow, offsets, stacking contexts, floats and sticky behavior.", objectives: ["Distinguish all five position values.", "Anchor absolute elements correctly.", "Reason about stacking contexts."], before: "Know normal flow and basic layout.", lessons: [
    ["Floats and flow-root", "float moves an element to a side so inline content can wrap around it. Modern layout usually prefers Flexbox or Grid. display: flow-root contains floats inside their parent.", ".container { display: flow-root; }\n.photo { float: left; margin-right: 1rem; }", "Choose floats for text wrapping, not as a default page layout system."],
    ["The five position values", "static is normal flow. relative keeps its space but accepts visual offsets. absolute leaves flow and uses the nearest positioned ancestor. fixed uses the viewport. sticky stays in flow until it reaches its inset threshold.", ".card { position: relative; }\n.card .badge { position: absolute; top: 8px; right: 8px; }", "Absolute positioning needs a containing block you can name."],
    ["Stacking and z-index", "z-index influences stacking for positioned elements and some layout items. A large z-index cannot escape an ancestor stacking context, so inspect the context hierarchy when a layer appears behind another.", ".modal { position: fixed; inset: 0; z-index: 100; }", "Z-index is a comparison inside stacking contexts, not a universal score."],
  ]},
  { number: "13", title: "CSS Attribute Selectors", deck: "Match links, language tags, data attributes and semantic states directly from HTML attributes.", objectives: ["Choose the correct attribute operator.", "Distinguish exact, word and substring matches.", "Use data and language attributes intentionally."], before: "Know element, class and ID selectors.", lessons: [
    ["Matching operators", "[attr] matches presence; [attr='value'] matches exact text; ~= matches a complete space-separated word; ^= starts with; $= ends with; *= matches a substring; |= matches an exact language token or its hyphenated form.", "a[href^='https://'] { color: seagreen; }\na[href$='.pdf'] { color: darkred; }", "~= is a whole word. *= is any substring."],
    ["Language and data attributes", "lang communicates content language. data-* stores application-specific values that CSS can match for styling or state cues. Keep behavior in JavaScript when the attribute changes behavior rather than appearance.", "[lang|='en'] { font-style: italic; }\n[data-state='current'] { font-weight: 700; }", "Attributes can describe state; they do not replace semantic HTML."],
    ["Attribute selectors in practice", "Combine attributes with classes and pseudo-classes to target a precise set without adding extra classes everywhere. Keep selectors understandable so future content still matches intentionally.", "button[aria-pressed='true'] { background: seagreen; }", "Start with the attribute relationship, then add a class only when the visual role needs it."],
  ]},
  { number: "14", title: "Responsive Web Design", deck: "Let content adapt to available space through fluid sizing, media queries, breakpoints and user preferences.", objectives: ["Build fluid foundations.", "Use content-driven breakpoints.", "Respect orientation and preference features."], before: "Know units, media queries and basic layout.", lessons: [
    ["Responsive foundations", "Responsive design adapts to available space and capabilities. Use flexible layouts, flexible images and content-driven rules instead of targeting a list of device names.", "img { max-width: 100%; height: auto; }\n.container { width: min(90%, 70rem); margin-inline: auto; }", "Make the content fluid before adding a breakpoint."],
    ["Media queries", "Media queries can test width, orientation, aspect ratio, resolution, hover, color scheme and reduced motion. A mobile-first min-width query adds capability as space grows.", "@media (min-width: 768px) { .cards { grid-template-columns: repeat(2, 1fr); } }", "A breakpoint should mark a layout change, not a device label."],
    ["Preferences and testing", "Use prefers-color-scheme and prefers-reduced-motion when the interface can adapt. Test narrow, wide, zoomed and touch contexts; inspect where text wraps and controls remain reachable.", "@media (prefers-color-scheme: dark) { body { background: #17221c; } }", "Responsive means usable at the edges, not just attractive at one width."],
  ]},
  { number: "15", title: "CSS Grid", deck: "Use a two-dimensional layout model for tracks, gaps, areas, placement and responsive galleries.", objectives: ["Define rows and columns.", "Place items with lines and areas.", "Build responsive tracks with minmax and auto-fit."], before: "Know Flexbox and basic sizing.", lessons: [
    ["Grid tracks and gaps", "Grid defines columns and rows together. gap adds space between tracks. grid-template-columns establishes the column structure; auto rows can use minmax for a lower bound and flexible growth.", ".layout { display: grid; grid-template-columns: 240px 1fr; gap: 24px; }", "Grid is two-dimensional; Flexbox is primarily one-dimensional."],
    ["Placement and areas", "grid-column and grid-row use start/end grid lines. 1 / -1 spans all explicit columns. Named grid areas make page regions easier to read and rearrange.", ".banner { grid-column: 1 / -1; }\n.layout { grid-template-areas: 'header header' 'sidebar main'; }", "Place the layout first; let content fill its named area."],
    ["Responsive galleries", "auto-fit and minmax let the browser choose how many tracks fit. Use min() inside a minimum when a card must not exceed the small viewport.", ".gallery { grid-template-columns: repeat(auto-fit, minmax(min(100%, 240px), 1fr)); }", "The minimum track size is the key to preventing narrow overflow."],
  ]},
  { number: "16", title: "CSS Animations", deck: "Define motion in stages, tune timing and repetition, and give users control over nonessential movement.", objectives: ["Connect keyframes to an element.", "Read animation shorthand.", "Respect reduced-motion preferences."], before: "Know transforms, transitions and media queries.", lessons: [
    ["Keyframes and properties", "@keyframes defines stages. animation-name connects the element to them; duration controls length; timing-function controls pacing. Delay, iteration count, direction, fill mode and play state refine behavior.", "@keyframes fadeIn { from { opacity: 0; transform: translateY(8px); } to { opacity: 1; transform: translateY(0); } }", "A keyframe name is only a definition until an animation uses it."],
    ["Transitions versus animations", "Transitions interpolate between state changes such as :hover. Keyframe animations can run independently and contain multiple stages. Prefer opacity and transform for smooth movement.", ".button { transition: transform 200ms ease; }\n.button:hover { transform: translateY(-2px); }", "Transitions respond to a change; animations can have their own timeline."],
    ["Accessible motion", "Respect prefers-reduced-motion and keep essential information available without animation. Disable nonessential animation and transitions for users who request less motion.", "@media (prefers-reduced-motion: reduce) {\n  .card { animation: none; }\n  .button { transition: none; }\n}", "Reduced motion is a user preference, not a design failure."],
  ]},
];

const guideNav = document.querySelector("#guide-nav");
const guideSearch = document.querySelector("#guide-search");
const article = document.querySelector("#guide-article");

function escapeHTML(value) {
  return String(value).replace(/[&<>\"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[char]));
}

function chapterId(number) {
  return number === "09" ? "flexbox" : `chapter-${number}`;
}

function renderNav(query = "") {
  const needle = query.trim().toLowerCase();
  guideNav.innerHTML = chapters.filter((chapter) => `${chapter.number} ${chapter.title} ${chapter.deck}`.toLowerCase().includes(needle)).map((chapter) => `<a href="#${chapterId(chapter.number)}"><span>${chapter.number}</span>${chapter.title}<small>${chapter.lessons.length} lessons</small></a>`).join("");
}

function renderLesson(lesson, index) {
  const [title, body, code, memory] = lesson;
  return `<section id="lesson-${index + 1}"><p class="lesson-number">Lesson ${String(index + 1).padStart(2, "0")}</p><h2>${title}</h2><p>${body}</p>${code ? `<pre>${escapeHTML(code)}</pre>` : ""}<p class="memory-note"><strong>Remember:</strong> ${memory}</p></section>`;
}

function renderFlexboxLab() {
  return `<section class="control-room" id="control-room"><p class="lesson-number">Interactive lab</p><h2>Flexbox Control Room</h2><p>Change one control at a time and watch the axes, item order and generated CSS update together.</p><div class="lab-layout"><form class="lab-controls" id="flex-controls"><label>Direction<select name="direction"><option>row</option><option>row-reverse</option><option>column</option><option>column-reverse</option></select></label><label>Wrapping<select name="wrap"><option>nowrap</option><option>wrap</option><option>wrap-reverse</option></select></label><label>Justify content<select name="justify"><option>flex-start</option><option>center</option><option>flex-end</option><option>space-between</option><option>space-around</option><option>space-evenly</option></select></label><label>Align items<select name="align"><option>stretch</option><option>flex-start</option><option>center</option><option>flex-end</option></select></label><button class="secondary-button" id="lab-reset" type="button">Reset controls</button></form><div class="lab-output"><div class="lab-preview" id="lab-preview" aria-label="Live Flexbox preview"><span class="lab-axis lab-main-axis" id="lab-main-axis">Main axis →</span><span class="lab-axis lab-cross-axis" id="lab-cross-axis">Cross axis ↓</span><div class="lab-item">1</div><div class="lab-item">2</div><div class="lab-item">3</div><div class="lab-item">4</div><div class="lab-item">5</div></div><p class="lab-explanation" id="lab-explanation" aria-live="polite"></p><pre id="generated-css"></pre></div></div></section>`;
}

function renderReview() {
  return `<section class="chapter-review" id="chapter-review"><p class="lesson-number">Chapter review</p><h2>Close the Flexbox file</h2><p>Answer five questions to check whether the axis model is ready for the investigation cases.</p><form id="flexbox-review"><fieldset data-question="1"><legend><span>01</span> Which property establishes a flex formatting context?</legend><label><input type="radio" name="q1" value="a"> <code>position: flex</code></label><label><input type="radio" name="q1" value="b"> <code>display: flex</code></label><label><input type="radio" name="q1" value="c"> <code>layout: flex</code></label><p class="answer-explanation" hidden></p></fieldset><fieldset data-question="2"><legend><span>02</span> With <code>flex-direction: row</code>, which property controls vertical alignment?</legend><label><input type="radio" name="q2" value="a"> <code>align-items</code></label><label><input type="radio" name="q2" value="b"> <code>justify-content</code></label><label><input type="radio" name="q2" value="c"> <code>flex-wrap</code></label><p class="answer-explanation" hidden></p></fieldset><fieldset data-question="3"><legend><span>03</span> What changes when <code>flex-direction</code> becomes <code>column</code>?</legend><label><input type="radio" name="q3" value="a"> Flexbox becomes two-dimensional</label><label><input type="radio" name="q3" value="b"> The main axis becomes vertical</label><label><input type="radio" name="q3" value="c"> The cross axis disappears</label><p class="answer-explanation" hidden></p></fieldset><fieldset data-question="4"><legend><span>04</span> Which value allows items to move onto another flex line?</legend><label><input type="radio" name="q4" value="a"> <code>flex-wrap: wrap</code></label><label><input type="radio" name="q4" value="b"> <code>flex-flow: nowrap</code></label><label><input type="radio" name="q4" value="c"> <code>align-items: stretch</code></label><p class="answer-explanation" hidden></p></fieldset><fieldset data-question="5"><legend><span>05</span> Which shorthand combines direction and wrapping?</legend><label><input type="radio" name="q5" value="a"> <code>flex: row wrap</code></label><label><input type="radio" name="q5" value="b"> <code>flex-flow: row wrap</code></label><label><input type="radio" name="q5" value="c"> <code>flex-direction: row wrap</code></label><p class="answer-explanation" hidden></p></fieldset><div class="review-actions"><button class="primary-button" type="submit">Check review →</button><button class="secondary-button" id="review-reset" type="button">Reset answers</button></div><p class="review-status" id="review-status" role="status" aria-live="polite">Answer all five questions to complete the review.</p></form></section>`;
}

function renderChapter(number) {
  const chapter = chapters.find((item) => item.number === number) || chapters[0];
  const id = chapterId(chapter.number);
  const jumpLinks = chapter.lessons.map((lesson, index) => `<a href="#lesson-${index + 1}">L${String(index + 1).padStart(2, "0")} ${lesson[0]}</a>`).join("");
  const labLink = chapter.lab ? `<a href="#control-room">Interactive lab</a>` : "";
  const next = chapters[Number(chapter.number) % chapters.length];
  article.id = id;
  article.innerHTML = `<p class="eyebrow">Chapter ${chapter.number} · ${chapter.title}</p><h1>${chapter.title} field guide</h1><p class="guide-deck">${chapter.deck}</p><div class="chapter-brief"><div><p class="lesson-number">Learning objectives</p><ul>${chapter.objectives.map((item) => `<li>${item}</li>`).join("")}</ul></div><div><p class="lesson-number">Before you begin</p><p>${chapter.before}</p><p><strong>Estimated chapter time:</strong> ${chapter.lessons.length * 5}–${chapter.lessons.length * 8} minutes</p></div></div><nav class="lesson-jump" aria-label="${chapter.title} lessons">${jumpLinks}${labLink}</nav>${chapter.lessons.map(renderLesson).join("")}${chapter.lab ? renderFlexboxLab() + renderReview() : ""}<section class="chapter-summary" id="chapter-summary"><div class="summary-stamp" id="summary-stamp">Reference ready</div><div><p class="lesson-number">Chapter ${chapter.number} summary</p><h2>Use the model in a case</h2><p id="chapter-status-text">Review the lessons, then test the idea against a focused debugging investigation in the Case Library.</p><ul><li id="lessons-status">✓ ${chapter.lessons.length} lessons available</li><li id="review-progress">→ Practice with the chapter cases</li><li id="case-progress">→ Practice with the chapter cases</li></ul><p class="next-chapter"><strong>Next suggested chapter:</strong> CH${next.number} ${next.title}</p></div></section><footer class="guide-case-link"><div><p class="eyebrow">Related investigation</p><h2>Continue in the Case Library</h2><p>Apply this chapter's ideas to a concrete CSS failure.</p></div><a class="primary-button button-link" href="cases.html">Browse cases →</a></footer>`;
  document.title = `Chapter ${chapter.number} ${chapter.title} | CSS Casebook`;
  renderNav(guideSearch.value);
}

renderNav();
guideSearch.addEventListener("input", (event) => renderNav(event.target.value));
window.addEventListener("hashchange", () => {
  const hash = location.hash.replace("#", "");
  const number = hash === "flexbox" ? "09" : hash.replace("chapter-", "");
  renderChapter(/^[0-9]{2}$/.test(number) ? number : "01");
});
renderChapter(location.hash ? (location.hash === "#flexbox" ? "09" : location.hash.replace("#chapter-", "")) : "01");
